# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

################################################################################
#
#   ORGANIZATIONS
#
#   This section defines the organizational identities that can be referenced
#   in the configuration profiles.
#
###############################################################################
Organizations:

    # SampleOrg defines an MSP using the sampleconfig. It should never be used
    # in production but may be used as a template for other definitions.
    - &OrdererOrg0
        Name: OrdererOrg0MSP
        ID: OrdererOrg0MSP
        MSPDir: crypto-config/ordererOrganizations/ordererorg0/msp
        Policies: &OrdererOrgPolicies
            Readers:
                Type: Signature
                Rule: "OR('OrdererOrg0MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererOrg0MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererOrg0MSP.admin')"
        OrdererEndpoints:
            - orderer0:7050

    - &JISTAP
        Name: JISTAP
        ID: JISTAP
        MSPDir: crypto-config/peerOrganizations/jistap/msp
        Policies: &JISTAPPolicies
            Readers:
                Type: Signature
                Rule: "OR('JISTAP.member')"
            Writers:
                Type: Signature
                Rule: "OR('JISTAP.member')"
            Admins:
                Type: Signature
                Rule: "OR('JISTAP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('JISTAP.member')"
        AnchorPeers:
            - Host: peer0
              Port: 7051

    - &JISTAP2
        Name: JISTAP2
        ID: JISTAP2
        MSPDir: crypto-config/peerOrganizations/jistap2/msp
        Policies: &JISTAP2Policies
            Readers:
                Type: Signature
                Rule: "OR('JISTAP2.member')"
            Writers:
                Type: Signature
                Rule: "OR('JISTAP2.member')"
            Admins:
                Type: Signature
                Rule: "OR('JISTAP2.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('JISTAP2.member')"
        AnchorPeers:
            - Host: peer2
              Port: 7051

Capabilities:
    Channel: &ChannelCapabilities
        #V1_4_4: true
        V2_0: true

    Orderer: &OrdererCapabilities
        #V1_4_4: true
        V2_0: true

    Application: &ApplicationCapabilities
        #V1_4_4: true
        V2_0: true

Application: &ApplicationDefaults
    ACLs:
          # ACL policy for _lifecycle's "CheckCommitReadiness" function
        _lifecycle/CheckCommitReadiness: /Channel/Application/Writers

        # ACL policy for _lifecycle's "CommitChaincodeDefinition" function
        _lifecycle/CommitChaincodeDefinition: /Channel/Application/Writers

        # ACL policy for _lifecycle's "QueryChaincodeDefinition" function
        _lifecycle/QueryChaincodeDefinition: /Channel/Application/Readers

        # ACL policy for _lifecycle's "QueryChaincodeDefinitions" function
        _lifecycle/QueryChaincodeDefinitions: /Channel/Application/Readers

        #---Lifecycle System Chaincode (lscc) function to policy mapping for access control---#

        # ACL policy for lscc's "getid" function
        lscc/ChaincodeExists: /Channel/Application/Readers

        # ACL policy for lscc's "getdepspec" function
        lscc/GetDeploymentSpec: /Channel/Application/Readers

        # ACL policy for lscc's "getccdata" function
        lscc/GetChaincodeData: /Channel/Application/Readers

        # ACL Policy for lscc's "getchaincodes" function
        lscc/GetInstantiatedChaincodes: /Channel/Application/Readers

        #---Query System Chaincode (qscc) function to policy mapping for access control---#

        # ACL policy for qscc's "GetChainInfo" function
        qscc/GetChainInfo: /Channel/Application/Readers

        # ACL policy for qscc's "GetBlockByNumber" function
        qscc/GetBlockByNumber: /Channel/Application/Readers

        # ACL policy for qscc's  "GetBlockByHash" function
        qscc/GetBlockByHash: /Channel/Application/Readers

        # ACL policy for qscc's "GetTransactionByID" function
        qscc/GetTransactionByID: /Channel/Application/Readers

        # ACL policy for qscc's "GetBlockByTxID" function
        qscc/GetBlockByTxID: /Channel/Application/Readers

        #---Configuration System Chaincode (cscc) function to policy mapping for access control---#

        # ACL policy for cscc's "GetConfigBlock" function
        cscc/GetConfigBlock: /Channel/Application/Readers

        # ACL policy for cscc's "GetConfigTree" function
        cscc/GetConfigTree: /Channel/Application/Readers

        # ACL policy for cscc's "SimulateConfigTreeUpdate" function
        cscc/SimulateConfigTreeUpdate: /Channel/Application/Readers

        #---Miscellaneous peer function to policy mapping for access control---#

        # ACL policy for invoking chaincodes on peer
        peer/Propose: /Channel/Application/Writers

        # ACL policy for chaincode to chaincode invocation
        peer/ChaincodeToChaincode: /Channel/Application/Readers

        #---Events resource to policy mapping for access control###---#

        # ACL policy for sending block events
        event/Block: /Channel/Application/Readers

        # ACL policy for sending filtered block events
        event/FilteredBlock: /Channel/Application/Readers

    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: etcdraft
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 30
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    TwoOrgsOrdererGenesis:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: etcdraft
            EtcdRaft:
                Consenters:
                    - Host: orderer0
                      Port: 7050
                      ClientTLSCert: /root/testnet/crypto-config/ordererOrganizations/ordererorg0/orderers/orderer0.ordererorg0/msp/signcerts/orderer0-cert.pem
                      ServerTLSCert: /root/testnet/crypto-config/ordererOrganizations/ordererorg0/orderers/orderer0.ordererorg0/msp/signcerts/orderer0-cert.pem
                    - Host: orderer1
                      Port: 7050
                      ClientTLSCert: /root/testnet/crypto-config/ordererOrganizations/ordererorg0/orderers/orderer1.ordererorg0/msp/signcerts/orderer1-cert.pem
                      ServerTLSCert: /root/testnet/crypto-config/ordererOrganizations/ordererorg0/orderers/orderer1.ordererorg0/msp/signcerts/orderer1-cert.pem
                    - Host: orderer2
                      Port: 7050
                      ClientTLSCert: /root/testnet/crypto-config/ordererOrganizations/ordererorg0/orderers/orderer2.ordererorg0/msp/signcerts/orderer2-cert.pem
                      ServerTLSCert: /root/testnet/crypto-config/ordererOrganizations/ordererorg0/orderers/orderer2.ordererorg0/msp/signcerts/orderer2-cert.pem
            Addresses:
                - orderer0:7050
                - orderer1:7050
                - orderer2:7050
            Organizations:
                - *OrdererOrg0
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *JISTAP
                    - *JISTAP2

    TwoOrgsChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *JISTAP
                - *JISTAP2
            Capabilities:
                <<: *ApplicationCapabilities
               
